// <auto-generated />
using System;
using Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Data.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20250414101637_site")]
    partial class site
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departments")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Mobile")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonnelCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Site")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7de05ab0-564d-49de-986a-bbf977e70579",
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            Family = "Manager",
                            IsDelete = false,
                            LockoutEnabled = false,
                            Mobile = "0",
                            Name = "Manager",
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEBVmwtKAZCwB5vQrSQOzAGjo6EQItNmhaLdwnEPd4Q4N7aoTBiYmDdUqTSLS3wHMtg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "af18f0b4-8f6d-4e16-b956-750144f3e4d0",
                            Site = 0,
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        },
                        new
                        {
                            Id = "9e224968-33e4-4652-b7b7-8574d048cdb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "457de0cb-4367-4939-b5eb-542191a662b1",
                            Email = "user@localhost.com",
                            EmailConfirmed = true,
                            Family = "User",
                            IsDelete = false,
                            LockoutEnabled = false,
                            Mobile = "0",
                            Name = "User",
                            NormalizedEmail = "USER@LOCALHOST.COM",
                            NormalizedUserName = "USER@LOCALHOST.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAENu/R9ZIq/ANzxX5EQy0MN86ie8onZipiGbGNTkHOi6mwycIuAEW7fK1AEf2atQJwA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8b5c7ddc-4304-4f49-a415-41430ac47561",
                            Site = 0,
                            TwoFactorEnabled = false,
                            UserName = "user@localhost.com"
                        });
                });

            modelBuilder.Entity("Domain.Models.BargeBaskoul", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"), 1L, 1);

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountChap")
                        .HasColumnType("int");

                    b.Property<string>("DateBarge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateBargiri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateBaskol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateChap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateNegahbani")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateTakhlie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateTimeBarge")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Ebtal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Sabt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("FlgEbtal")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgSabt")
                        .HasColumnType("bit");

                    b.Property<long?>("GhabzBaskolID")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDAnbar")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDBargiri")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDBaskul")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDDarkhastAmaliat")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDGheymatGozari")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDKala")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDMarkaz")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDNegahbani")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDNemoneGiri")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDRanande")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDShakhs")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDTafsili")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDTafsili2")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDTakhlie")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDTypeBaskul")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDTypeJabejaiee")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDTypeMarkazHamz")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDVasile")
                        .HasColumnType("bigint");

                    b.Property<int?>("IDWebBarge")
                        .HasColumnType("int");

                    b.Property<string>("KarbarTaeedKonandeDA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Karbar_Ebtal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Karbar_Ins")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Karbar_Sabt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Karbar_Up")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("KerayeHaml")
                        .HasColumnType("real");

                    b.Property<float?>("MablaghBaskol")
                        .HasColumnType("real");

                    b.Property<float?>("MeghdarDarkhastAmaliat")
                        .HasColumnType("real");

                    b.Property<float?>("NerkhKala")
                        .HasColumnType("real");

                    b.Property<string>("OnvanRanandeh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShomareMashin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeBarge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeBargiri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeBaskol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeChap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeNegahbani")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeTakhlie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeVaznKhali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeVaznPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TypeBarge")
                        .HasColumnType("int");

                    b.Property<int?>("TypeBargeAnbar")
                        .HasColumnType("int");

                    b.Property<int?>("TypeGheymatGozari")
                        .HasColumnType("int");

                    b.Property<float?>("VanKhali")
                        .HasColumnType("real");

                    b.Property<float?>("VaznBasteBandi")
                        .HasColumnType("real");

                    b.Property<float?>("VaznPor")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("BargeBaskouls");
                });

            modelBuilder.Entity("Domain.Models.BaseTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GroupName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Value")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ValueFarsi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BaseTables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupName = "TransactionType",
                            IsDeleted = false,
                            ValueFarsi = "فروش"
                        },
                        new
                        {
                            Id = 2,
                            GroupName = "RequestPropertyUsage",
                            IsDeleted = false,
                            ValueFarsi = "سایر"
                        });
                });

            modelBuilder.Entity("Domain.Models.Baskoul", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScaleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Site")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("baskouls");
                });

            modelBuilder.Entity("Domain.Models.BuilderProfile.BuilderProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AnnualActivityVolumeBaseTableId")
                        .HasColumnType("int");

                    b.Property<int?>("BusinessPriorityBaseTableId")
                        .HasColumnType("int");

                    b.Property<int?>("BuyingAndSellingBaseTableId")
                        .HasColumnType("int");

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CooperationDuration")
                        .HasColumnType("int");

                    b.Property<string>("CooperationField")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CooperationResults")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool?>("Corporate")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int?>("DesignBaseTableId")
                        .HasColumnType("int");

                    b.Property<int?>("EducationBaseTableId")
                        .HasColumnType("int");

                    b.Property<int?>("ExecutionBaseTableId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MainOccupation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("ManagementContract")
                        .HasColumnType("bit");

                    b.Property<int?>("MaritalStatusBaseTableId")
                        .HasColumnType("int");

                    b.Property<int?>("MaterialSupplyBaseTableId")
                        .HasColumnType("int");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int?>("NumberOfDaughters")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfSons")
                        .HasColumnType("int");

                    b.Property<bool?>("Partnership")
                        .HasColumnType("bit");

                    b.Property<int?>("PermitObtainingBaseTableId")
                        .HasColumnType("int");

                    b.Property<bool?>("Personal")
                        .HasColumnType("bit");

                    b.Property<bool?>("PreviousCooperation")
                        .HasColumnType("bit");

                    b.Property<bool?>("Reconstruction")
                        .HasColumnType("bit");

                    b.Property<bool?>("Renovation")
                        .HasColumnType("bit");

                    b.Property<string>("WorkAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BuilderProfiles");
                });

            modelBuilder.Entity("Domain.Models.BuilderProfile.BuilderProfileCompletedProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("BuilderProfileId")
                        .HasColumnType("int");

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConstructionQualityBaseTableId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("NumberOfFloors")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalArea")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BuilderProfileId");

                    b.ToTable("BuilderProfileCompletedProjects");
                });

            modelBuilder.Entity("Domain.Models.BuilderProfile.BuilderProfileEstimatedNeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BuilderProfileId")
                        .HasColumnType("int");

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("EstimatedResolutionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FollowUpMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("NeedDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProjectNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ResponsiblePerson")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BuilderProfileId");

                    b.ToTable("BuilderProfileEstimatedNeeds");
                });

            modelBuilder.Entity("Domain.Models.BuilderProfile.BuilderProfileFollowUpResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BuilderProfileId")
                        .HasColumnType("int");

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("NeedDescription")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ProjectNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Reason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Result")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BuilderProfileId");

                    b.ToTable("BuilderProfileFollowUpResults");
                });

            modelBuilder.Entity("Domain.Models.BuilderProfile.BuilderProfileOngoingAndUpcomingProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("BuilderProfileId")
                        .HasColumnType("int");

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CurrentStage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int?>("NumberOfFloors")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TotalArea")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuilderProfileId");

                    b.ToTable("BuilderProfileOngoingAndUpcomingProjects");
                });

            modelBuilder.Entity("Domain.Models.BuilderProfile.RebuildAbility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Family")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Mobile")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Modifiedby")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RebuildabilityBaseTableId")
                        .HasColumnType("int");

                    b.Property<string>("Representative")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RebuildAbilities");
                });

            modelBuilder.Entity("Domain.Models.CodeMarkaz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkazURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CodeMarkazs");
                });

            modelBuilder.Entity("Domain.Models.DesignExecution.DesignExecutionEmployer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AdmissionsSpecialistUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("Datedmission")
                        .HasColumnType("datetime2");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IntroducingPerson")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProjectAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestAddress")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("RequestBarbecueBaseTableId")
                        .HasColumnType("int");

                    b.Property<string>("RequestBathroomCeilingMaterial")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestBathroomDescription")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RequestBathroomFloorMaterial")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestBathroomLighting")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestBathroomWallMaterial")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestBedroomCeilingMaterial")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestBedroomDescription")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RequestBedroomFloorMaterial")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("RequestBedroomHasIroningBoard")
                        .HasColumnType("bit");

                    b.Property<bool?>("RequestBedroomHasLibrary")
                        .HasColumnType("bit");

                    b.Property<bool?>("RequestBedroomHasWardrobe")
                        .HasColumnType("bit");

                    b.Property<string>("RequestBedroomLighting")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestBedroomWallMaterial")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestBetweenCabinetsMaterial")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestBuildingSpecificationsDescription")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double?>("RequestCabinetHeight")
                        .HasColumnType("float");

                    b.Property<string>("RequestCabinetType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RequestChildNumber")
                        .HasColumnType("int");

                    b.Property<int?>("RequestCoolingSystemBaseTableId")
                        .HasColumnType("int");

                    b.Property<string>("RequestCountertopMaterial")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RequestElectricalSystemBaseTableId")
                        .HasColumnType("int");

                    b.Property<string>("RequestEntranceCeilingMaterial")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestEntranceDescription")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RequestEntranceFloorMaterial")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("RequestEntranceHasPlantSpace")
                        .HasColumnType("bit");

                    b.Property<string>("RequestEntranceLighting")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestEntranceWallMaterial")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestFacilitiesDescription")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RequestFatherName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestFavoriteColor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RequestFireAlarmSystemBaseTableId")
                        .HasColumnType("int");

                    b.Property<string>("RequestHandleType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("RequestHasBuiltInGasCooktop")
                        .HasColumnType("bit");

                    b.Property<bool?>("RequestHasCamera")
                        .HasColumnType("bit");

                    b.Property<bool>("RequestHasGasCooktopSpace")
                        .HasColumnType("bit");

                    b.Property<bool>("RequestHasMicrowaveSpace")
                        .HasColumnType("bit");

                    b.Property<bool>("RequestHasOvenSpace")
                        .HasColumnType("bit");

                    b.Property<bool?>("RequestHasPlantSpaceOnTerrace")
                        .HasColumnType("bit");

                    b.Property<bool?>("RequestHasShowcaseDesk")
                        .HasColumnType("bit");

                    b.Property<bool?>("RequestHasShowcaseDressingTable")
                        .HasColumnType("bit");

                    b.Property<string>("RequestHasTrashBinSpace")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RequestHeatingSystemBaseTableId")
                        .HasColumnType("int");

                    b.Property<string>("RequestKitchenCeilingMaterial")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestKitchenDescription")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RequestKitchenFloorMaterial")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestKitchenLighting")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestKitchenWallMaterial")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestLandlinePhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RequestLivingRoomCeilingMaterial")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestLivingRoomDescription")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RequestLivingRoomFloorMaterial")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("RequestLivingRoomHasShowcase")
                        .HasColumnType("bit");

                    b.Property<bool?>("RequestLivingRoomHasTVWall")
                        .HasColumnType("bit");

                    b.Property<string>("RequestLivingRoomLighting")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestLivingRoomWallMaterial")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RequestMasterDoorMaterialBaseTableId")
                        .HasColumnType("int");

                    b.Property<string>("RequestMobilePhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RequestMunicipalArea")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RequestPropertyAddress")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("RequestPropertyArea")
                        .HasColumnType("int");

                    b.Property<int?>("RequestPropertyLength")
                        .HasColumnType("int");

                    b.Property<int?>("RequestPropertyPositionBaseTableId")
                        .HasColumnType("int");

                    b.Property<int?>("RequestPropertyUsageBaseTableId")
                        .HasColumnType("int");

                    b.Property<string>("RequestPropertyUsageOthers")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("RequestPropertyWidth")
                        .HasColumnType("int");

                    b.Property<int?>("RequestRenovationReasonsBaseTableId")
                        .HasColumnType("int");

                    b.Property<string>("RequestRenovationReasonsOthers")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("RequestRequiredBathrooms")
                        .HasColumnType("int");

                    b.Property<int?>("RequestRequiredBedrooms")
                        .HasColumnType("int");

                    b.Property<int?>("RequestRequiredKitchenSize")
                        .HasColumnType("int");

                    b.Property<int?>("RequestRequiredLivingRoomSize")
                        .HasColumnType("int");

                    b.Property<int?>("RequestRequiredStorageSpace")
                        .HasColumnType("int");

                    b.Property<int?>("RequestRequiredTerraceSpace")
                        .HasColumnType("int");

                    b.Property<int?>("RequestRequiredToilets")
                        .HasColumnType("int");

                    b.Property<bool>("RequestSecondarySpacesRequiredCloakroom")
                        .HasColumnType("bit");

                    b.Property<bool>("RequestSecondarySpacesRequiredLaundry")
                        .HasColumnType("bit");

                    b.Property<string>("RequestSecondarySpacesRequiredOthers")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RequestSecondarySpacesRequiredSecondKitchen")
                        .HasColumnType("bit");

                    b.Property<string>("RequestStorageCabinet")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestSuperCabinet")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestTerraceCeilingMaterial")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestTerraceDescription")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RequestTerraceFloorMaterial")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestTerraceLighting")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestTerraceWallMaterial")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RequestYearOfManufacture")
                        .HasColumnType("int");

                    b.Property<string>("Tel")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int?>("TypeOfAdmissionBaseTableId")
                        .HasColumnType("int");

                    b.Property<bool>("TypeOfProjectAreaDesign")
                        .HasColumnType("bit");

                    b.Property<int?>("TypeOfProjectEmployerBaseTableId")
                        .HasColumnType("int");

                    b.Property<bool>("TypeOfProjectFacadeDesign")
                        .HasColumnType("bit");

                    b.Property<bool>("TypeOfProjectInteriorDesign")
                        .HasColumnType("bit");

                    b.Property<bool>("TypeOfProjectPlanDesign")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VisitAdmissionsSpecialistUserId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisitEmployerComments")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("VisitExistingSituation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("VisitImageUrl1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VisitImageUrl2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VisitImageUrl3")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VisitImageUrl4")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VisitImageUrl5")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("VisitWasItMeasured")
                        .HasColumnType("bit");

                    b.Property<bool>("VisitWasItPhotoTaken")
                        .HasColumnType("bit");

                    b.Property<bool>("VisitWasItVideoTaken")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("TypeOfAdmissionBaseTableId");

                    b.ToTable("DesignExecutionEmployers");
                });

            modelBuilder.Entity("Domain.Models.DesignExecution.DesignExecutionEmployerFollowUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Actions")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DesignExecutionEmployerId")
                        .HasColumnType("int");

                    b.Property<int>("FollowUpMethodBaseTableId")
                        .HasColumnType("int");

                    b.Property<int>("FollowUpOutcomeBaseTableId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("NextFollowUpMethod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DesignExecutionEmployerId");

                    b.ToTable("DesignExecutionEmployerFollowUps");
                });

            modelBuilder.Entity("Domain.Models.DesignExecution.DesignExecutionEmployerVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AdmissionsSpecialistUserId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("DesignExecutionEmployerId")
                        .HasColumnType("int");

                    b.Property<string>("EmployerComments")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExistingSituation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("WasItMeasured")
                        .HasColumnType("bit");

                    b.Property<bool>("WasItPhotoTaken")
                        .HasColumnType("bit");

                    b.Property<bool>("WasItVideoTaken")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DesignExecutionEmployerId");

                    b.ToTable("DesignExecutionEmployerVisits");
                });

            modelBuilder.Entity("Domain.Models.Mabani", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("CIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateIns")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUp")
                        .HasColumnType("datetime2");

                    b.Property<long?>("IDLinq")
                        .HasColumnType("bigint");

                    b.Property<string>("KarbarIns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KarbarUp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Onvan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Mabanis");
                });

            modelBuilder.Entity("Domain.Models.ObjectForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupNameFarsi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameFarsi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ObjectForms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Departement = "realestate",
                            GroupName = "Applicant",
                            GroupNameFarsi = "متقاضی",
                            Name = "Applicant",
                            NameFarsi = "مشاهده متقاضی",
                            UserName = "user1"
                        },
                        new
                        {
                            Id = 2,
                            Departement = "design",
                            GroupName = "Form",
                            GroupNameFarsi = "فرم",
                            Name = "FileRebuildability",
                            NameFarsi = "پروفایل بازسازی",
                            UserName = "user2"
                        });
                });

            modelBuilder.Entity("Domain.Models.ObjectFormUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("ObjectFormId")
                        .HasColumnType("int");

                    b.Property<string>("Supplier_")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("User_")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ObjectFormId");

                    b.ToTable("ObjectFormUsers");
                });

            modelBuilder.Entity("Domain.Models.ObjectTransactionTypeUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("ObjectId")
                        .HasColumnType("int");

                    b.Property<string>("SupplierId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ObjectTransactionTypeUsers");
                });

            modelBuilder.Entity("Domain.Models.Site", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("Domain.Models.UserSite", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("SiteId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSites");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "cac43a6e-f7bb-4448-baaf-1add431ccbbf",
                            ConcurrencyStamp = "55e62da2-2c86-4438-afdd-4025c16802d4",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "cbc43a8e-f7bb-4445-baaf-1add431ffbbf",
                            ConcurrencyStamp = "dde4cd0a-c55c-4c1b-874d-8d2e33c0c7eb",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            RoleId = "cbc43a8e-f7bb-4445-baaf-1add431ffbbf"
                        },
                        new
                        {
                            UserId = "9e224968-33e4-4652-b7b7-8574d048cdb9",
                            RoleId = "cac43a6e-f7bb-4448-baaf-1add431ccbbf"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Baskoul", b =>
                {
                    b.HasOne("Domain.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.BuilderProfile.BuilderProfileCompletedProject", b =>
                {
                    b.HasOne("Domain.Models.BuilderProfile.BuilderProfile", "BuilderProfile")
                        .WithMany("BuilderProfileCompletedProjects")
                        .HasForeignKey("BuilderProfileId");

                    b.Navigation("BuilderProfile");
                });

            modelBuilder.Entity("Domain.Models.BuilderProfile.BuilderProfileEstimatedNeed", b =>
                {
                    b.HasOne("Domain.Models.BuilderProfile.BuilderProfile", "BuilderProfile")
                        .WithMany("BuilderProfileEstimatedNeeds")
                        .HasForeignKey("BuilderProfileId");

                    b.Navigation("BuilderProfile");
                });

            modelBuilder.Entity("Domain.Models.BuilderProfile.BuilderProfileFollowUpResult", b =>
                {
                    b.HasOne("Domain.Models.BuilderProfile.BuilderProfile", "BuilderProfile")
                        .WithMany("BuilderProfileFollowUpResults")
                        .HasForeignKey("BuilderProfileId");

                    b.Navigation("BuilderProfile");
                });

            modelBuilder.Entity("Domain.Models.BuilderProfile.BuilderProfileOngoingAndUpcomingProject", b =>
                {
                    b.HasOne("Domain.Models.BuilderProfile.BuilderProfile", "BuilderProfile")
                        .WithMany("BuilderProfileOngoingAndUpcomingProjects")
                        .HasForeignKey("BuilderProfileId");

                    b.Navigation("BuilderProfile");
                });

            modelBuilder.Entity("Domain.Models.DesignExecution.DesignExecutionEmployer", b =>
                {
                    b.HasOne("Domain.Models.BaseTable", "TypeOfAdmissionBaseTable")
                        .WithMany("DesignExecutionEmployerTypeOfAdmissionBaseTable")
                        .HasForeignKey("TypeOfAdmissionBaseTableId");

                    b.Navigation("TypeOfAdmissionBaseTable");
                });

            modelBuilder.Entity("Domain.Models.DesignExecution.DesignExecutionEmployerFollowUp", b =>
                {
                    b.HasOne("Domain.Models.DesignExecution.DesignExecutionEmployer", "DesignExecutionEmployers")
                        .WithMany("DesignExecutionEmployerFollowUps")
                        .HasForeignKey("DesignExecutionEmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DesignExecutionEmployers");
                });

            modelBuilder.Entity("Domain.Models.DesignExecution.DesignExecutionEmployerVisit", b =>
                {
                    b.HasOne("Domain.Models.DesignExecution.DesignExecutionEmployer", "DesignExecutionEmployers")
                        .WithMany("DesignExecutionEmployerVisits")
                        .HasForeignKey("DesignExecutionEmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DesignExecutionEmployers");
                });

            modelBuilder.Entity("Domain.Models.ObjectFormUser", b =>
                {
                    b.HasOne("Domain.Models.ObjectForm", "ObjectForm")
                        .WithMany("ObjectFormUsers")
                        .HasForeignKey("ObjectFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjectForm");
                });

            modelBuilder.Entity("Domain.Models.UserSite", b =>
                {
                    b.HasOne("Domain.Models.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.BaseTable", b =>
                {
                    b.Navigation("DesignExecutionEmployerTypeOfAdmissionBaseTable");
                });

            modelBuilder.Entity("Domain.Models.BuilderProfile.BuilderProfile", b =>
                {
                    b.Navigation("BuilderProfileCompletedProjects");

                    b.Navigation("BuilderProfileEstimatedNeeds");

                    b.Navigation("BuilderProfileFollowUpResults");

                    b.Navigation("BuilderProfileOngoingAndUpcomingProjects");
                });

            modelBuilder.Entity("Domain.Models.DesignExecution.DesignExecutionEmployer", b =>
                {
                    b.Navigation("DesignExecutionEmployerFollowUps");

                    b.Navigation("DesignExecutionEmployerVisits");
                });

            modelBuilder.Entity("Domain.Models.ObjectForm", b =>
                {
                    b.Navigation("ObjectFormUsers");
                });
#pragma warning restore 612, 618
        }
    }
}

