// <auto-generated />
using System;
using Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Data.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20260707130728_AddUserSiteAccesses")]
    partial class AddUserSiteAccesses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departments")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Mobile")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonnelCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SelectedSiteId")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("WindowsToken")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            AccessFailedCount = 0,
                            CodMarkaz = "1",
                            ConcurrencyStamp = "7de05ab0-564d-49de-986a-bbf977e70579",
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            Family = "Manager",
                            IsDelete = false,
                            LockoutEnabled = false,
                            Mobile = "0",
                            Name = "Manager",
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEBVmwtKAZCwB5vQrSQOzAGjo6EQItNmhaLdwnEPd4Q4N7aoTBiYmDdUqTSLS3wHMtg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "af18f0b4-8f6d-4e16-b956-750144f3e4d0",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        },
                        new
                        {
                            Id = "9e224968-33e4-4652-b7b7-8574d048cdb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "457de0cb-4367-4939-b5eb-542191a662b1",
                            Email = "user@localhost.com",
                            EmailConfirmed = true,
                            Family = "User",
                            IsDelete = false,
                            LockoutEnabled = false,
                            Mobile = "0",
                            Name = "User",
                            NormalizedEmail = "USER@LOCALHOST.COM",
                            NormalizedUserName = "USER@LOCALHOST.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAENu/R9ZIq/ANzxX5EQy0MN86ie8onZipiGbGNTkHOi6mwycIuAEW7fK1AEf2atQJwA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8b5c7ddc-4304-4f49-a415-41430ac47561",
                            TwoFactorEnabled = false,
                            UserName = "user@localhost.com"
                        });
                });

            modelBuilder.Entity("Domain.Models.BargeBaskoul", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountChap")
                        .HasColumnType("int");

                    b.Property<string>("CreateIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DateBarge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateBargiri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateBaskol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateChap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateInsToWeb")
                        .HasColumnType("datetime2");

                    b.Property<string>("DateNegahbani")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateTakhlie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateTimeBarge")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpToWeb")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Ebtal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Sabt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Up")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("FlgEbtal")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgSabt")
                        .HasColumnType("bit");

                    b.Property<long?>("GhabzBaskolID")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDAnbar")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDBargiri")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDBaskul")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDDarkhastAmaliat")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDGheymatGozari")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDKala")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDMarkaz")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDNegahbani")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDNemoneGiri")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDRanande")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDShakhs")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDTafsili")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDTafsili2")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDTakhlie")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDTypeBaskul")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDTypeJabejaiee")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDTypeMarkazHamz")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDVasile")
                        .HasColumnType("bigint");

                    b.Property<int?>("IDWebBarge")
                        .HasColumnType("int");

                    b.Property<string>("KarbarTaeedKonandeDA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Karbar_Ebtal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Karbar_Ins")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Karbar_Sabt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Karbar_Up")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("KerayeHaml")
                        .HasColumnType("real");

                    b.Property<float?>("MablaghBaskol")
                        .HasColumnType("real");

                    b.Property<float?>("MeghdarDarkhastAmaliat")
                        .HasColumnType("real");

                    b.Property<string>("ModifyIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float?>("NerkhKala")
                        .HasColumnType("real");

                    b.Property<string>("OnvanRanandeh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShomareMashin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeBarge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeBargiri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeBaskol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeChap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeNegahbani")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeTakhlie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeVaznKhali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeVaznPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TypeBarge")
                        .HasColumnType("int");

                    b.Property<int?>("TypeBargeAnbar")
                        .HasColumnType("int");

                    b.Property<int?>("TypeGheymatGozari")
                        .HasColumnType("int");

                    b.Property<float?>("VanKhali")
                        .HasColumnType("real");

                    b.Property<float?>("VaznBasteBandi")
                        .HasColumnType("real");

                    b.Property<float?>("VaznPor")
                        .HasColumnType("real");

                    b.Property<int?>("siteId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("BargeBaskouls");
                });

            modelBuilder.Entity("Domain.Models.BaseTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GroupName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifyIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Value")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ValueFarsi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BaseTables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupName = "TransactionType",
                            IsDeleted = false,
                            ValueFarsi = "فروش"
                        },
                        new
                        {
                            Id = 2,
                            GroupName = "RequestPropertyUsage",
                            IsDeleted = false,
                            ValueFarsi = "سایر"
                        });
                });

            modelBuilder.Entity("Domain.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("APIURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("AutoAsync")
                        .HasColumnType("bit");

                    b.Property<string>("CoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MarkazURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifyIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutoAsync = true,
                            CoName = "شرکت بین‌المللی سیستم‌ها و اتوماسیون (ایریسا)",
                            CodMarkaz = "1"
                        });
                });

            modelBuilder.Entity("Domain.Models.GhabzSerialTracker", b =>
                {
                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<string>("CreateIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifyIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Serial")
                        .HasColumnType("int");

                    b.HasKey("CodMarkaz", "Year");

                    b.ToTable("GhabzSerialTrackers");
                });

            modelBuilder.Entity("Domain.Models.Mabani", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateIns")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUp")
                        .HasColumnType("datetime2");

                    b.Property<long?>("IDLinq")
                        .HasColumnType("bigint");

                    b.Property<string>("KarbarIns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KarbarUp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifyIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Onvan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Mabanis");
                });

            modelBuilder.Entity("Domain.Models.ObjectForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Departement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupNameFarsi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifyIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameFarsi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ObjectForms");
                });

            modelBuilder.Entity("Domain.Models.ObjectFormUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ModifyIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ObjectFormId")
                        .HasColumnType("int");

                    b.Property<string>("Supplier_")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("User_")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ObjectFormId");

                    b.ToTable("ObjectFormUsers");
                });

            modelBuilder.Entity("Domain.Models.ReportSetting", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateIns")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUp")
                        .HasColumnType("datetime2");

                    b.Property<string>("FactoryAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FactoryPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Fax")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KarbarIns")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KarbarUp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ModifyIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OfficeAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OfficePhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Postcode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShomareBaznegari")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShomareSanad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TarikhBaznegari")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Telfax")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("ReportSettings");
                });

            modelBuilder.Entity("Domain.Models.Settings", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Date_Ins")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Up")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Defaults")
                        .HasColumnType("bit");

                    b.Property<bool?>("Delet")
                        .HasColumnType("bit");

                    b.Property<string>("Karbar_Ins")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Karbar_Up")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifyIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SettingName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SettingParameter")
                        .HasColumnType("int");

                    b.Property<double?>("SettingValue")
                        .HasColumnType("float");

                    b.Property<string>("Tozihat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("api_hash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("dore_id")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Domain.Models.UserSiteAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifyIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.HasIndex("UserId", "SiteId")
                        .IsUnique();

                    b.ToTable("UserSiteAccesses");
                });

            modelBuilder.Entity("Domain.Models.Weighbridge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifyIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScaleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<int>("WeighbridgeSiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WeighbridgeSiteId");

                    b.ToTable("Weighbridges");
                });

            modelBuilder.Entity("Domain.Models.WeighbridgeSite", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CreateIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifyIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CompanyId");

                    b.ToTable("WeighbridgeSites");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "cac43a6e-f7bb-4448-baaf-1add431ccbbf",
                            ConcurrencyStamp = "55e62da2-2c86-4438-afdd-4025c16802d4",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "abc12def-1234-4567-89ab-1234567890ab",
                            ConcurrencyStamp = "39a9015e-1958-405b-a4ea-25bf2249e783",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            RoleId = "abc12def-1234-4567-89ab-1234567890ab"
                        },
                        new
                        {
                            UserId = "9e224968-33e4-4652-b7b7-8574d048cdb9",
                            RoleId = "cac43a6e-f7bb-4448-baaf-1add431ccbbf"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodMarkaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ObjectFormUser", b =>
                {
                    b.HasOne("Domain.Models.ObjectForm", "ObjectForm")
                        .WithMany("ObjectFormUsers")
                        .HasForeignKey("ObjectFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjectForm");
                });

            modelBuilder.Entity("Domain.Models.UserSiteAccess", b =>
                {
                    b.HasOne("Domain.Models.WeighbridgeSite", "Site")
                        .WithMany("UserSiteAccesses")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.AppUser", "User")
                        .WithMany("SiteAccesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Weighbridge", b =>
                {
                    b.HasOne("Domain.Models.WeighbridgeSite", "WeighbridgeSite")
                        .WithMany("Weighbridges")
                        .HasForeignKey("WeighbridgeSiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WeighbridgeSite");
                });

            modelBuilder.Entity("Domain.Models.WeighbridgeSite", b =>
                {
                    b.HasOne("Domain.Models.Company", "Company")
                        .WithMany("WeighbridgeSites")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.AppUser", b =>
                {
                    b.Navigation("SiteAccesses");
                });

            modelBuilder.Entity("Domain.Models.Company", b =>
                {
                    b.Navigation("WeighbridgeSites");
                });

            modelBuilder.Entity("Domain.Models.ObjectForm", b =>
                {
                    b.Navigation("ObjectFormUsers");
                });

            modelBuilder.Entity("Domain.Models.WeighbridgeSite", b =>
                {
                    b.Navigation("UserSiteAccesses");

                    b.Navigation("Weighbridges");
                });
#pragma warning restore 612, 618
        }
    }
}
